site_name: Yiges

copyright: >
  Copyright &copy; 2018 - 2022 Yiges.M.x., all rights reserved. –
  <a href="#__consent">Change cookie settings</a>

repo_url: https://github.com/YigesMx/yiges

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: zh
  custom_dir: overrides

  features:
    - navigation.instant # 懒惰加载
    - navigation.tracking # 自动追踪
    - navigation.tabs # 顶部标签栏
    - navigation.tabs.sticky # 顶部标签栏固定
    # - navigation.expand # 自动展开所有分类
    - navigation.indexes # index.md
    - toc.follow # toc
    - navigation.top # 回到顶部

    - header.autohide

    # - announce.dismiss

    #md头部选项：
    # ---
    # hide:
    #   - navigation
    #   - toc
    # ---
  
  icon:
    repo: fontawesome/brands/git-alt

  font:
    text: Roboto
    code: Roboto Mono
  
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: cyan
      accent: lime
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: cyan
      accent: lime
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    


plugins:
  - search:
      lang: ja
  - tags:
      tags_file: index.md
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      # fallback_to_build_date: true



extra:
  # generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YigesMx
    # - icon: fontawesome/brands/qq
    #   link: https://github.com/YigesMx
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    #cookies:
    #  analytics: Custom name
    actions:
      - accept
      - manage

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      linenums: true
      auto_title: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#   - assets/js/mdui.min.js

# extra_css:
#   - assets/css/mdui.min.css

nav:
  - 主页: index.md
  - 分享: 分享/index.md
  - 折腾: 折腾/index.md
  