site_name: Yiges

copyright: >
  Copyright &copy; 2018 - 2022 Yiges.M.x., all rights reserved. –
  <a href="#__consent">Change cookie settings</a>

repo_url: https://github.com/YigesMx/yiges

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: zh
  custom_dir: overrides

  features:
    # - navigation.instant # 懒惰加载
    - navigation.tracking # 自动追踪
    - navigation.tabs # 顶部标签栏
    - navigation.tabs.sticky # 顶部标签栏固定
    # - navigation.expand # 自动展开所有分类
    - navigation.indexes # index.md
    - toc.follow # toc
    - navigation.top # 回到顶部

    - header.autohide

    # - announce.dismiss

    #md头部选项：
    # ---
    # hide:
    #   - navigation
    #   - toc
    # ---
  
  icon:
    repo: fontawesome/brands/git-alt

  font:
    text: Roboto
    code: Roboto Mono
  
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: cyan
      accent: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: cyan
      accent: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    


plugins:
  - search:
      lang: ja
  - tags:
      tags_file: index.md
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      # fallback_to_build_date: true



extra:
  # generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YigesMx
    # - icon: fontawesome/brands/qq
    #   link: https://github.com/YigesMx
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    #cookies:
    #  analytics: Custom name
    actions:
      - accept
      - manage

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      auto_title: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/mdui.js
  # - assets/js/mind.js

extra_css:
  - assets/css/mdui.css

nav:
  - 索引器: index.md
  - 终端机: terminal.md
  - 智域:
    - Domain/index.md
    - Ark:
      - Domain/Ark/index.md
      - CS:
        - 关于链接: Domain/Ark/CS/2022-09-25-different-links.md
        - 关于Git: Domain/Ark/CS/2022-09-26-git.md
        - Web-Server-Building: Domain/Ark/CS/2022-10-07-web-server-building.md
    - Halo: Domain/Halo/index.md
  - 致远:
    - Reach/index.md
    - 折腾实录:
      - canves-nest.js: Reach/折腾实录/2022-09-25-canves-nest-js.md
      - Listary与Edge书签导出: Reach/折腾实录/2022-10-27-Listary-and-fav-export.md
  - 丰饶:
    - Harvest/index.md
    - 影音资源:
      - 常用资源站: Harvest/影音/常用资源站.md
      - 相关工具: Harvest/影音/相关工具.md
      - 影评及回顾:
        - Harvest/影音/review/index.md
        - 2022-0910-LOTR-TROP: Harvest/影音/review/2022-0910-LOTR-TROP.md
    - 工具:
      - Harvest/工具/index.md
  - 滑流空间: slipspace.md
  