# ========== Site Information ==========
site_name: Yiges
site_url: https://www.yiges.site
site_author: Yiges.M.x.
site_description: >
  这个站点的主要是我个人整理的一些内容和资源分享，将来的 Projects 也会发布在这上面，欢迎大家共同讨论，提出建议，一起交流。


copyright: >
  Copyright &copy; 2018 - NOW Yiges.M.x., all rights reserved.
  &nbsp;|&nbsp;
  <a href="https://beian.miit.gov.cn/" target="_blank">蜀ICP备2024099498号-1</a>
  &nbsp;|&nbsp;
  <div style="display: inline-block; height: 10px; verticle-align: center;"><img src="/assets/img/public-security.png" alt="公安" style="height: 100%;"></div>
  <a href="https://beian.mps.gov.cn/#/query/webSearch?code=11010802044966" rel="noreferrer" target="_blank">京公网安备11010802044966</a>
  &nbsp;|&nbsp;
  <a href="#__consent">Change cookie settings</a>

repo_url: https://github.com/YigesMx/yiges
edit_uri: edit/main/docs/

validation:
  # absolute_links: ignore
  unrecognized_links: ignore

# ========== Navigation ==========
nav:
  - index.md
  - terminal.md
  - slingshot.md
  - 智域:
    - Domain/index.md
    - Ark:
      - Domain/Ark/index.md
      - AI:
        - Domain/Ark/AI/2024-05-01-introduction-to-transformer.md
        - Domain/Ark/AI/2024-02-03-ai-fundamentals.md
      - Dev:
        - Domain/Ark/Dev/2022-09-26-git.md
        - Domain/Ark/Dev/2022-09-25-different-links.md
      - Research:
        - Domain/Ark/Research/2022-09-25-matplotlib.md
    - Halo:
      - Domain/Halo/index.md
  - 致远:
    - Reach/index.md
    - 没事儿爱折腾:
      - Reach/没事儿爱折腾/2024-09-28-alfred-workflow.md
      - Reach/没事儿爱折腾/2024-09-23-deploy-syncthing.md
      - Reach/没事儿爱折腾/2024-09-19-RevolverMaps.md
      - Reach/没事儿爱折腾/2024-09-19-vue-in-mkdocs.md
      - Reach/没事儿爱折腾/2024-09-11-deploy-searxng.md
      - Reach/没事儿爱折腾/2022-10-27-Listary-and-fav-export.md
      - Reach/没事儿爱折腾/2022-09-25-canves-nest-js.md
    - 干活儿也折腾:
      - Reach/干活儿也折腾/2024-09-20-pandoc-md-latex.md

  - 丰饶:
    - Harvest/index.md
    - 工具和项目:
      - Harvest/工具和项目/index.md
      - Harvest/工具和项目/2024-10-12-typst.md
      - Harvest/工具和项目/2024-09-28-listary.md
      - Harvest/工具和项目/2024-09-28-alfred.md
      - Harvest/工具和项目/2024-09-28-shell-gpt.md
      - Harvest/工具和项目/2024-09-26-tldr.md
      - Harvest/工具和项目/2024-09-23-sync-tools.md
      - Harvest/工具和项目/2024-09-20-pandoc.md
      - Harvest/工具和项目/2024-09-15-windows-quicklook.md
      - Harvest/工具和项目/2024-09-15-mac-quicklook-plugin.md
    - 影音资源:
      - Harvest/影音/常用资源站.md
      - Harvest/影音/我的歌单.md
  - slipspace.md

# ========== Extra Loading & Process ==========

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - assets/js/config-katex.js

  - https://unpkg.com/vue@3/dist/vue.global.prod.js
  - https://unpkg.com/naive-ui@2.39.0/dist/index.prod.js
  - assets/js/yiges-vue-app-manager.js

  - assets/js/auto-update-copyright-date.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css
  - assets/css/globe-fix.css
  - assets/css/yiges-horizontal-cards.css
  - assets/css/theme-fix.css

watch:
  - includes
  - overrides

# ========== Theme Configuration & Plugins ==========
theme:
  name: material
  language: zh
  custom_dir: overrides

  logo: assets/logo.png
  favicon: assets/favicon.png
  icon: # about icons: https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
    repo: fontawesome/brands/git-alt
  
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant # 单页应用模式，无刷新加载
    - navigation.instant.progress # 加载进度条

    - navigation.tracking # 自动追踪
    - navigation.tabs # 顶部标签栏
    - navigation.tabs.sticky # 顶部标签栏固定
    # - navigation.expand # 自动展开所有分类
    - navigation.indexes # index.md
    - navigation.top # 回到顶部
    - navigation.footer # 页脚导航

    - toc.follow # toc

    - header.autohide # 自动隐藏标题栏

    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮，点击后定位
    - search.share # 搜索分享

    - announce.dismiss # 公告栏关闭

    - content.action.edit # 编辑按钮
    - content.action.view # 查看源码按钮
  
  palette: # 调色板
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      accent: cyan
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      accent: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


plugins:
  # - privacy
  - social:
      cards_layout_options:
        font_family: Noto Sans SC
  - search:
      lang: zh
  - tags:
      tags_file: slingshot.md
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
  - add-number:
        strict_mode: False
        order: 2

extra:
  # generator: false # Made with Material for MkDocs notice
  homepage: https://www.yiges.site
  social:  # 页脚社交链接
    - icon: fontawesome/brands/github
      link: https://github.com/YigesMx
      name: GitHub
    - icon: material/web
      link: https://www.yiges.site
      name: Homepage
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/83527634
      name: Bilibili
  analytics:
    provider: google
    property: G-J8WMV9GVD0
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    #cookies:
    #  analytics: Custom name
    actions:
      - accept
      - reject
      - manage

# ========== Markdown Extensions ==========
markdown_extensions:

  # === 基本文法增强 ===
  # 跳过 \ 后的一切字符的转义
  - pymdownx.escapeall:
      nbsp: true # \空格转义为 &nbsp;
      hardbreak: true # \换行转义为 <br>，可以可视地替代 Markdown 的两个空格换行
  # 若#后无空格，则不会被识别为标题
  - pymdownx.saneheaders
  # 智能符号增强，(tm) (c) (r) -> ™ © ®, +/- --> <-- <--> =/= 1/4 1st 2nd
  - pymdownx.smartsymbols
  # 为数学公式渲染器 (MathJax/KaTeX) 提供支持，保留原始公式
  - pymdownx.arithmatex:
      generic: true
  # 表情
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # 高级代码块
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # 代码高亮，详见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      auto_title: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  # 强调优化
  - pymdownx.betterem:
      smart_enable: all
  # 上标，使用 ^^xx^^ 显示插入的文本，使用 ^xxx^ 显示作为上标的文本
  - pymdownx.caret
  # 下标，使用 ~xx~ 显示删除的文本，使用 ~xxx~ 显示作为下标的文本
  - pymdownx.tilde
  # 自动链接，自动识别链接，另有特别多 shorthand，参考 https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: YigesMx
      repo: yiges
      provider: github


  # === 高阶语法增强 ===
  # GFW Checkbox List
  - pymdownx.tasklist:
      custom_checkbox: true
  # 键盘按键，++command+option+c++
  - pymdownx.keys
  # 缩写提示，文末加上 *[abbr]: Abbreviation
  - abbr 
  # 提示框，!!! note||info||warning||danger||success||... "Title" ，换行缩进Content ；可折叠则改为 ???+ ，+代表默认展开
  - admonition 
  - pymdownx.details
  # 脚注，[^1]，文末加上 [^1]: 脚注内容
  - footnotes 
  # 表格
  - tables
  # 定义列表，: term : definition
  - def_list
  # 批改语法，{--删除--}，{++添加++}，{~~ 替换为 ~> xxx ~~}，{==高亮==}，{>>注释<<}
  - pymdownx.critic:
      mode: view
  # 高亮标记，==highlight==
  - pymdownx.mark
  # mkdocs-material 扩展：Annotation， 含有 annotate 类的 block，使用 (1) 添加注释，在块后使用有序列表添加注释内容
  # mkdocs-material 扩展：Grids，详见 https://squidfunk.github.io/mkdocs-material/reference/grids/
  # mkdocs-material 扩展：Button，link 加上 .md-button 类


  # === 文档结构增强 ===
  # 目录
  - toc: 
      permalink: false
  # 片段，详见 https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.snippets:
      base_path: 
        - includes
      check_paths: true
      auto_append:
        - global_abbreviations.md
  # 分栏，使用 === "TabName" 换行缩进+内容，来新建一个 Tab ，https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.tabbed:
      alternate_style: true

  # === HTML/CSS增强 ===
  - attr_list # HTML属性列表，{#id .class key=value}
  - md_in_html # 在HTML中使用Markdown，<div markdown="1"||markdown>...</div>